version: '2'
services:
  web:
    image: nginx:alpine
    restart: always 
    volumes:
      - ./public:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - /var/log/jslearning:/var/log/nginx
    networks:
      - neco_link
networks:
  neco_link:
    external: true 

